'use client';

import { useState } from 'react';

/**
 * ============================================================
 * JOURNAL GURU - TRAVEL JOURNAL EDITION
 * ============================================================
 * 
 * This is the main page of our journal prompt generator app
 * customized for travel journaling. It contains a form where 
 * users can input their travel reflections and get personalized 
 * journal prompts generated by AI.
 */

export default function Home() {
  // ============================================================
  // STATE MANAGEMENT
  // ============================================================
  const [formData, setFormData] = useState({
    moment: '',
    sensory: '',
    tension: '',
    person: '',
    concept: ''
  });

  const [customMoment, setCustomMoment] = useState('');
  const [customSensory, setCustomSensory] = useState('');
  const [customTension, setCustomTension] = useState('');
  const [customPerson, setCustomPerson] = useState('');
  const [customConcept, setCustomConcept] = useState('');

  const [prompts, setPrompts] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // Warm, professional color palette
  const colors = {
    background: '#f5f1e8',
    backgroundAlt: '#faf8f3',
    white: '#fff',
    primary: '#c9a876',
    primaryDark: '#b59465',
    text: '#5a4a42',
    textLight: '#8b7d78',
    border: '#e8ddd5',
    highlight: '#fff9e6',
    error: '#dc2626',
    success: '#10b981'
  };

  const selectStyles = (colors) => ({
    padding: '0.875rem',
    fontSize: '1rem',
    borderRadius: '0.5rem',
    border: `2px solid ${colors.border}`,
    backgroundColor: colors.white,
    color: colors.text,
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'border-color 0.2s',
    outline: 'none',
    width: '100%'
  });

  const inputStyles = (colors) => ({
    padding: '0.875rem',
    fontSize: '1rem',
    borderRadius: '0.5rem',
    border: `2px solid ${colors.border}`,
    backgroundColor: colors.backgroundAlt,
    color: colors.text,
    fontFamily: 'inherit',
    outline: 'none',
    transition: 'border-color 0.2s',
    width: '100%'
  });

  // ============================================================
  // EVENT HANDLERS
  // ============================================================
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleCustomChange = (fieldName, value) => {
    if (fieldName === 'moment') setCustomMoment(value);
    if (fieldName === 'sensory') setCustomSensory(value);
    if (fieldName === 'tension') setCustomTension(value);
    if (fieldName === 'person') setCustomPerson(value);
    if (fieldName === 'concept') setCustomConcept(value);
  };

  const handleCopyAll = async () => {
    try {
      await navigator.clipboard.writeText(prompts);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setPrompts('');
    setCopied(false);

    // Prepare form data with custom values if "Other" is selected
    const submitData = {
      ...formData,
      moment: formData.moment === 'Other' ? customMoment : formData.moment,
      sensory: formData.sensory === 'Other' ? customSensory : formData.sensory,
      tension: formData.tension === 'Other' ? customTension : formData.tension,
      person: formData.person === 'Other' ? customPerson : formData.person,
      concept: formData.concept === 'Other' ? customConcept : formData.concept,
    };

    try {
      const response = await fetch('/api/generate-prompts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(submitData),
      });
      if (!response.ok) throw new Error('Failed to generate prompts');
      const data = await response.json();
      setPrompts(data.prompts);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // ============================================================
  // RENDER COMPONENT
  // ============================================================
  return (
    <div style={{
      minHeight: '100vh',
      background: `linear-gradient(135deg, ${colors.background} 0%, ${colors.backgroundAlt} 100%)`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '2rem 1rem'
    }}>
      <div style={{
        maxWidth: '800px',
        width: '100%',
        display: 'flex',
        flexDirection: 'column'
      }}>
        {/* Header Section - Logo and Description */}
        <div style={{
          textAlign: 'center',
          marginBottom: '3rem'
        }}>
          <img 
            src="/journal-guru-logo.jpg" 
            alt="Journal Guru"
            style={{
              maxWidth: '400px',
              width: '100%',
              height: 'auto',
              marginBottom: '1.5rem',
              borderRadius: '1rem',
              boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)'
            }}
          />
          <p style={{
            fontSize: '1.125rem',
            color: colors.textLight,
            fontWeight: '400',
            marginBottom: 0,
            lineHeight: '1.6'
          }}>
            AI-powered journal prompts tailored to your travel experience
          </p>
        </div>

        {/* Main Form Container */}
        <div style={{
          backgroundColor: colors.white,
          borderRadius: '1rem',
          padding: '2.5rem',
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05), 0 1px 3px rgba(0, 0, 0, 0.1)',
          marginBottom: '2rem',
          border: `1px solid rgba(139, 125, 120, 0.1)`
        }}>
          <form onSubmit={handleSubmit}>
            {/* Form Fields Grid - Responsive layout */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
              gap: '2rem',
              marginBottom: '2rem'
            }}>
              {/* Question 1: Moment or Encounter */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <label htmlFor="moment" style={{
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  color: colors.text
                }}>What moment or encounter from this place is asking something of you?</label>
                <select id="moment" name="moment" value={formData.moment} onChange={handleInputChange} required style={selectStyles(colors)}
                onFocus={(e) => e.target.style.borderColor = colors.primary}
                onBlur={(e) => e.target.style.borderColor = colors.border}
                >
                  <option value="">Select an experience</option>
                  <option value="Something that surprised or unsettled me">Something that surprised or unsettled me</option>
                  <option value="A difference I didn't expect to notice">A difference I didn't expect to notice</option>
                  <option value="A connection I didn't anticipate forming">A connection I didn't anticipate forming</option>
                  <option value="Something I realized I didn't understand about myself">Something I realized I didn't understand about myself</option>
                  <option value="A beauty or truth I want to hold onto">A beauty or truth I want to hold onto</option>
                  <option value="Other">Other</option>
                </select>
                {formData.moment === 'Other' && (
                  <input
                    type="text"
                    placeholder="Describe the moment or encounter"
                    value={customMoment}
                    onChange={(e) => handleCustomChange('moment', e.target.value)}
                    required
                    style={{...inputStyles(colors), marginTop: '0.5rem'}}
                    onFocus={(e) => e.target.style.borderColor = colors.primary}
                    onBlur={(e) => e.target.style.borderColor = colors.border}
                  />
                )}
              </div>

              {/* Question 2: Sensory Detail */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <label htmlFor="sensory" style={{
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  color: colors.text
                }}>What sensory detail keeps returning to you?</label>
                <select id="sensory" name="sensory" value={formData.sensory} onChange={handleInputChange} required style={selectStyles(colors)}
                onFocus={(e) => e.target.style.borderColor = colors.primary}
                onBlur={(e) => e.target.style.borderColor = colors.border}
                >
                  <option value="">Select a sensory detail</option>
                  <option value="A sound, smell, or texture">A sound, smell, or texture</option>
                  <option value="How your body feels in this place">How your body feels in this place</option>
                  <option value="A gesture or way people move">A gesture or way people move</option>
                  <option value="The landscape or architecture">The landscape or architecture</option>
                  <option value="Other">Other</option>
                </select>
                {formData.sensory === 'Other' && (
                  <input
                    type="text"
                    placeholder="Describe the sensory detail"
                    value={customSensory}
                    onChange={(e) => handleCustomChange('sensory', e.target.value)}
                    required
                    style={{...inputStyles(colors), marginTop: '0.5rem'}}
                    onFocus={(e) => e.target.style.borderColor = colors.primary}
                    onBlur={(e) => e.target.style.borderColor = colors.border}
                  />
                )}
              </div>

              {/* Question 3: Tension between home and here */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <label htmlFor="tension" style={{
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  color: colors.text
                }}>What's the tension between "home" and "here"?</label>
                <select id="tension" name="tension" value={formData.tension} onChange={handleInputChange} required style={selectStyles(colors)}
                onFocus={(e) => e.target.style.borderColor = colors.primary}
                onBlur={(e) => e.target.style.borderColor = colors.border}
                >
                  <option value="">Select a tension</option>
                  <option value="How I thought I'd feel vs. how I actually feel">How I thought I'd feel vs. how I actually feel</option>
                  <option value="What I brought with me vs. what I'm finding here">What I brought with me vs. what I'm finding here</option>
                  <option value="The comfort of the familiar vs. the richness of the strange">The comfort of the familiar vs. the richness of the strange</option>
                  <option value="How I'm different in this context">How I'm different in this context</option>
                  <option value="Other">Other</option>
                </select>
                {formData.tension === 'Other' && (
                  <input
                    type="text"
                    placeholder="Describe the tension you're experiencing"
                    value={customTension}
                    onChange={(e) => handleCustomChange('tension', e.target.value)}
                    required
                    style={{...inputStyles(colors), marginTop: '0.5rem'}}
                    onFocus={(e) => e.target.style.borderColor = colors.primary}
                    onBlur={(e) => e.target.style.borderColor = colors.border}
                  />
                )}
              </div>

              {/* Question 4: Person, story, or voice */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <label htmlFor="person" style={{
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  color: colors.text
                }}>Is there a person, story, or voice you want to center?</label>
                <select id="person" name="person" value={formData.person} onChange={handleInputChange} required style={selectStyles(colors)}
                onFocus={(e) => e.target.style.borderColor = colors.primary}
                onBlur={(e) => e.target.style.borderColor = colors.border}
                >
                  <option value="">Select a focus</option>
                  <option value="Something someone here told me or showed me">Something someone here told me or showed me</option>
                  <option value="A conversation that changed how I think">A conversation that changed how I think</option>
                  <option value="An observation about how people navigate life here">An observation about how people navigate life here</option>
                  <option value="A piece of local wisdom or perspective">A piece of local wisdom or perspective</option>
                  <option value="My own internal dialogue and discovery">My own internal dialogue and discovery</option>
                  <option value="Other">Other</option>
                </select>
                {formData.person === 'Other' && (
                  <input
                    type="text"
                    placeholder="Describe the person, story, or voice"
                    value={customPerson}
                    onChange={(e) => handleCustomChange('person', e.target.value)}
                    required
                    style={{...inputStyles(colors), marginTop: '0.5rem'}}
                    onFocus={(e) => e.target.style.borderColor = colors.primary}
                    onBlur={(e) => e.target.style.borderColor = colors.border}
                  />
                )}
              </div>

              {/* Question 5: Concept to explore */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <label htmlFor="concept" style={{
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  color: colors.text
                }}>What concept would you like to explore in this writing?</label>
                <select id="concept" name="concept" value={formData.concept} onChange={handleInputChange} required style={selectStyles(colors)}
                onFocus={(e) => e.target.style.borderColor = colors.primary}
                onBlur={(e) => e.target.style.borderColor = colors.border}
                >
                  <option value="">Select a concept</option>
                  <option value="Arrival">Arrival</option>
                  <option value="Stranger">Stranger</option>
                  <option value="Hospitality">Hospitality</option>
                  <option value="Ground">Ground</option>
                  <option value="Wonder">Wonder</option>
                  <option value="Silence">Silence</option>
                  <option value="Belonging">Belonging</option>
                  <option value="Courage">Courage</option>
                  <option value="Presense">Presense</option>
                  <option value="Gratitude">Gratitude</option>
                  <option value="Other">Other</option>
                </select>
                {formData.concept === 'Other' && (
                  <input
                    type="text"
                    placeholder="Describe the concept"
                    value={customConcept}
                    onChange={(e) => handleCustomChange('concept', e.target.value)}
                    required
                    style={{...inputStyles(colors), marginTop: '0.5rem'}}
                    onFocus={(e) => e.target.style.borderColor = colors.primary}
                    onBlur={(e) => e.target.style.borderColor = colors.border}
                  />
                )}
              </div>
            </div>

            {/* Submit Button */}
            <button type="submit" disabled={loading} style={{
              width: '100%',
              padding: '1rem 1.5rem',
              fontSize: '1rem',
              fontWeight: '600',
              backgroundColor: colors.primary,
              color: colors.white,
              border: 'none',
              borderRadius: '0.5rem',
              cursor: loading ? 'not-allowed' : 'pointer',
              transition: 'all 0.2s',
              opacity: loading ? 0.7 : 1,
              boxShadow: `0 4px 6px rgba(201, 168, 118, 0.2)`,
              letterSpacing: '0.3px'
            }}
            onMouseEnter={(e) => !loading && (e.target.style.backgroundColor = colors.primaryDark)}
            onMouseLeave={(e) => !loading && (e.target.style.backgroundColor = colors.primary)}
            >
              {loading ? 'Generating Prompts...' : 'Generate Journal Prompts'}
            </button>
          </form>
        </div>

        {/* Error Message Display */}
        {error && (
          <div style={{
            backgroundColor: '#fee2e2',
            borderRadius: '0.5rem',
            padding: '1.25rem',
            marginBottom: '2rem',
            border: '1px solid #fca5a5'
          }}>
            <p style={{
              color: colors.error,
              fontSize: '0.95rem',
              margin: 0
            }}>{error}</p>
          </div>
        )}

        {/* Results Display - Shows generated prompts */}
        {prompts && (
          <div style={{
            backgroundColor: colors.white,
            borderRadius: '1rem',
            padding: '2.5rem',
            boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05), 0 1px 3px rgba(0, 0, 0, 0.1)',
            border: `1px solid rgba(139, 125, 120, 0.1)`,
            animation: 'fadeIn 0.3s ease-in'
          }}>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: '2rem',
              flexWrap: 'wrap',
              gap: '1rem'
            }}>
              <h2 style={{
                fontSize: '1.5rem',
                fontWeight: '700',
                color: colors.text,
                margin: 0
              }}>Your Personalized Journal Prompts</h2>
              <button
                onClick={handleCopyAll}
                style={{
                  padding: '0.75rem 1.5rem',
                  backgroundColor: copied ? colors.success : 'transparent',
                  color: copied ? colors.white : colors.primary,
                  border: `2px solid ${copied ? colors.success : colors.primary}`,
                  borderRadius: '0.5rem',
                  fontSize: '0.95rem',
                  fontWeight: '600',
                  cursor: 'pointer',
                  transition: 'all 0.2s',
                  whiteSpace: 'nowrap'
                }}
                onMouseEnter={(e) => !copied && (e.target.style.backgroundColor = '#f0e6d2')}
                onMouseLeave={(e) => !copied && (e.target.style.backgroundColor = 'transparent')}
              >
                {copied ? '✓ Copied!' : 'Copy All'}
              </button>
            </div>
            <div style={{
              background: `linear-gradient(135deg, ${colors.highlight} 0%, ${colors.backgroundAlt} 100%)`,
              borderLeft: `5px solid ${colors.primary}`,
              padding: '2rem',
              borderRadius: '0.5rem',
              fontSize: '1.05rem',
              lineHeight: '1.8',
              color: colors.text,
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
              boxShadow: `0 2px 4px rgba(201, 168, 118, 0.1)`
            }}>{prompts}</div>
          </div>
        )}
      </div>

      {/* Footer */}
      <footer style={{
        marginTop: '4rem',
        textAlign: 'center',
        color: colors.textLight,
        fontSize: '0.9rem',
        opacity: 0.8
      }}>
        <p>By Curt & Godwins</p>
      </footer>

      <style>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      `}</style>
    </div>
  );
}
