'use client';

import { useState } from 'react';

/**
 * ============================================================
 * JOURNAL GURU - MAIN PAGE COMPONENT
 * ============================================================
 * 
 * This is the main page of our journal prompt generator app.
 * It contains a form where users can input their preferences
 * and get personalized journal prompts generated by AI.
 */

export default function Home() {
  // ============================================================
  // STATE MANAGEMENT
  // ============================================================
  const [formData, setFormData] = useState({
    age: '',
    issue: '',
    lens: '',
    style: '',
    numPrompts: '3-5'
  });

  const [prompts, setPrompts] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // ============================================================
  // EVENT HANDLERS
  // ============================================================
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setPrompts('');
    try {
      const response = await fetch('/api/generate-prompts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });
      if (!response.ok) throw new Error('Failed to generate prompts');
      const data = await response.json();
      setPrompts(data.prompts);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // ============================================================
  // RENDER COMPONENT
  // ============================================================
  return (
    <div className="page-container">
      <div className="content-wrapper">
        {/* Header Section - Title and Description */}
        <div className="header-section">
          <h1 className="header-title">Journal Guru</h1>
          <p className="header-subtitle">AI-powered journal prompts tailored to your life situation</p>
        </div>

        {/* Main Form Container */}
        <div className="form-container">
          <form onSubmit={handleSubmit}>
            {/* Form Fields Grid - Responsive layout */}
            <div className="form-grid">
              {/* Age Range Selection */}
              <div className="form-field">
                <label htmlFor="age" className="form-label">Age Range</label>
                <select id="age" name="age" value={formData.age} onChange={handleInputChange} required className="form-select">
                  <option value="">Select age range</option>
                  <option value="18-25">18-25</option>
                  <option value="26-35">26-35</option>
                  <option value="36-45">36-45</option>
                  <option value="46-55">46-55</option>
                  <option value="56-65">56-65</option>
                  <option value="65+">65+</option>
                </select>
              </div>

              {/* Life Situation Selection */}
              <div className="form-field">
                <label htmlFor="issue" className="form-label">Life Situation</label>
                <select id="issue" name="issue" value={formData.issue} onChange={handleInputChange} required className="form-select">
                  <option value="">Select your situation</option>
                  <option value="Career transition">Career transition</option>
                  <option value="Relationship challenges">Relationship challenges</option>
                  <option value="Personal growth">Personal growth</option>
                  <option value="Stress management">Stress management</option>
                  <option value="Life purpose">Life purpose</option>
                  <option value="Health concerns">Health concerns</option>
                  <option value="Family dynamics">Family dynamics</option>
                  <option value="Financial stress">Financial stress</option>
                </select>
              </div>

              {/* Philosophical/Spiritual Lens Selection */}
              <div className="form-field">
                <label htmlFor="lens" className="form-label">Philosophical/Spiritual Lens</label>
                <select id="lens" name="lens" value={formData.lens} onChange={handleInputChange} required className="form-select">
                  <option value="">Select your perspective</option>
                  <option value="Mindfulness and meditation">Mindfulness and meditation</option>
                  <option value="Stoic philosophy">Stoic philosophy</option>
                  <option value="Buddhist principles">Buddhist principles</option>
                  <option value="Christian spirituality">Christian spirituality</option>
                  <option value="Secular humanism">Secular humanism</option>
                  <option value="Cognitive behavioral therapy">Cognitive behavioral therapy</option>
                  <option value="Positive psychology">Positive psychology</option>
                </select>
              </div>

              {/* Writing Style Selection */}
              <div className="form-field">
                <label htmlFor="style" className="form-label">Style/Focus</label>
                <select id="style" name="style" value={formData.style} onChange={handleInputChange} required className="form-select">
                  <option value="">Select your preferred style</option>
                  <option value="Gentle and reflective">Gentle and reflective</option>
                  <option value="Direct and challenging">Direct and challenging</option>
                  <option value="Creative and imaginative">Creative and imaginative</option>
                  <option value="Analytical and structured">Analytical and structured</option>
                  <option value="Compassionate and supportive">Compassionate and supportive</option>
                </select>
              </div>
            </div>

            {/* Number of Prompts Selection */}
            <div className="form-field" style={{ marginTop: '1.5rem' }}>
              <label htmlFor="numPrompts" className="form-label">Number of Prompts</label>
              <select id="numPrompts" name="numPrompts" value={formData.numPrompts} onChange={handleInputChange} className="form-select">
                <option value="1">1 prompt</option>
                <option value="3-5">3-5 prompts</option>
                <option value="5-7">5-7 prompts</option>
              </select>
            </div>

            {/* Submit Button */}
            <button type="submit" disabled={loading} className="btn-primary" style={{ marginTop: '1.5rem' }}>
              {loading ? 'Generating Prompts...' : 'Generate Journal Prompts'}
            </button>
          </form>
        </div>

        {/* Error Message Display */}
        {error && (
          <div className="error-message">
            <p className="error-text">{error}</p>
          </div>
        )}

        {/* Results Display - Shows generated prompts */}
        {prompts && (
          <div className="results-container">
            <h2 className="results-title">Your Personalized Journal Prompts</h2>
            <div className="prompts-content">{prompts}</div>
          </div>
        )}
      </div>
    </div>
  );
}
