'use client';

import { useState } from 'react';

/**
 * ============================================================
 * JOURNAL GURU - MAIN PAGE COMPONENT
 * ============================================================
 * 
 * This is the main page of our journal prompt generator app.
 * It contains a form where users can input their preferences
 * and get personalized journal prompts generated by AI.
 * 
 * Key Features:
 * - Form with dropdown selections for personalization
 * - Real-time form validation
 * - Loading states during AI processing
 * - Error handling for failed requests
 * - Responsive design that works on mobile and desktop
 */

export default function Home() {
  // ============================================================
  // STATE MANAGEMENT
  // ============================================================
  // These variables store the current state of our app:
  
  // Form data - stores what the user has selected in the form
  const [formData, setFormData] = useState({
    age: '',           // User's age range (18-25, 26-35, etc.)
    issue: '',         // Life situation they want to explore
    lens: '',          // Philosophical/spiritual perspective
    style: '',         // Preferred writing style
    numPrompts: '3-5'  // How many prompts they want
  });
  
  // Generated prompts from the AI
  const [prompts, setPrompts] = useState('');
  
  // Loading state - shows when we're waiting for AI response
  const [loading, setLoading] = useState(false);
  
  // Error messages - displays if something goes wrong
  const [error, setError] = useState('');

  // ============================================================
  // EVENT HANDLERS
  // ============================================================
  
  /**
   * Handles changes to form inputs
   * Updates the formData state whenever user selects something
   */
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  /**
   * Handles form submission
   * Sends user's preferences to our AI API and displays results
   */
  const handleSubmit = async (e) => {
    e.preventDefault(); // Prevents page from refreshing
    
    // Show loading state and clear previous results
    setLoading(true);
    setError('');
    setPrompts('');

    try {
      // Send form data to our API endpoint
      const response = await fetch('/api/generate-prompts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData), // Convert form data to JSON
      });

      // Check if the request was successful
      if (!response.ok) {
        throw new Error('Failed to generate prompts');
      }

      // Get the AI-generated prompts from the response
      const data = await response.json();
      setPrompts(data.prompts);
    } catch (err) {
      // If something goes wrong, show error message
      setError(err.message);
    } finally {
      // Always stop loading, whether success or failure
      setLoading(false);
    }
  };

  // ============================================================
  // RENDER COMPONENT
  // ============================================================
  // This is what the user sees on the webpage
  
  return (
    <div className="page-container">
      <div className="content-wrapper">
        {/* Header Section - Title and Description */}
        <div className="header-section">
          <h1 className="header-title">
            Journal Guru
          </h1>
          <p className="header-subtitle">
            AI-powered journal prompts tailored to your life situation
          </p>
        </div>

        {/* Main Form Container */}
        <div className="form-container">
          <form onSubmit={handleSubmit}>
            {/* Form Fields Grid - Responsive layout */}
            <div className="form-grid">
              {/* Age Range Selection */}
              <div className="form-field">
                <label htmlFor="age" className="form-label">
                  Age Range
                </label>
                <select
                  id="age"
                  name="age"
                  value={formData.age}
                  onChange={handleInputChange}
                  required
                  className="form-select"
                >
                  <option value="">Select age range</option>
                  <option value="18-25">18-25</option>
                  <option value="26-35">26-35</option>
                  <option value="36-45">36-45</option>
                  <option value="46-55">46-55</option>
                  <option value="56-65">56-65</option>
                  <option value="65+">65+</option>
                </select>
              </div>

              {/* Life Situation Selection */}
              <div className="form-field">
                <label htmlFor="issue" className="form-label">
                  Life Situation
                </label>
                <select
                  id="issue"
                  name="issue"
                  value={formData.issue}
                  onChange={handleInputChange}
                  required
                  className="form-select"
                >
                  <option value="">Select your situation</option>
                  <option value="Career transition">Career transition</option>
                  <option value="Relationship challenges">Relationship challenges</option>
                  <option value="Personal growth">Personal growth</option>
                  <option value="Stress management">Stress management</option>
                  <option value="Life purpose">Life purpose</option>
                  <option value="Health concerns">Health concerns</option>
                  <option value="Family dynamics">Family dynamics</option>
                  <option value="Financial stress">Financial stress</option>
                </select>
              </div>

              {/* Philosophical/Spiritual Lens Selection */}
              <div className="form-field">
                <label htmlFor="lens" className="form-label">
                  Philosophical/Spiritual Lens
                </label>
                <select
                  id="lens"
                  name="lens"
                  value={formData.lens}
                  onChange={handleInputChange}
                  required
                  className="form-select"
                >
                  <option value="">Select your perspective</option>
                  <option value="Mindfulness and meditation">Mindfulness and meditation</option>
                  <option value="Stoic philosophy">Stoic philosophy</option>
                  <option value="Buddhist principles">Buddhist principles</option>
                  <option value="Christian spirituality">Christian spirituality</option>
                  <option value="Secular humanism">Secular humanism</option>
                  <option value="Cognitive behavioral therapy">Cognitive behavioral therapy</option>
                  <option value="Positive psychology">Positive psychology</option>
                </select>
              </div>

              {/* Writing Style Selection */}
              <div className="form-field">
                <label htmlFor="style" className="form-label">
                  Style/Focus
                </label>
                <select
                  id="style"
                  name="style"
                  value={formData.style}
                  onChange={handleInputChange}
                  required
                  className="form-select"
                >
                  <option value="">Select your preferred style</option>
                  <option value="Gentle and reflective">Gentle and reflective</option>
                  <option value="Direct and challenging">Direct and challenging</option>
                  <option value="Creative and imaginative">Creative and imaginative</option>
                  <option value="Analytical and structured">Analytical and structured</option>
                  <option value="Compassionate and supportive">Compassionate and supportive</option>
                </select>
              </div>
            </div>

            {/* Number of Prompts Selection */}
            <div className="form-field" style={{ marginTop: '1.5rem' }}>
              <label htmlFor="numPrompts" className="form-label">
                Number of Prompts
              </label>
              <select
                id="numPrompts"
                name="numPrompts"
                value={formData.numPrompts}
                onChange={handleInputChange}
                className="form-select"
              >
                <option value="1">1 prompt</option>
                <option value="3-5">3-5 prompts</option>
                <option value="5-7">5-7 prompts</option>
              </select>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading}
              className="btn-primary"
              style={{ marginTop: '1.5rem' }}
            >
              {loading ? 'Generating Prompts...' : 'Generate Journal Prompts'}
            </button>
          </form>
        </div>

        {/* Error Message Display */}
        {error && (
          <div className="error-message">
            <p className="error-text">{error}</p>
          </div>
        )}

        {/* Results Display - Shows generated prompts */}
        {prompts && (
          <div className="results-container">
            <h2 className="results-title">Your Personalized Journal Prompts</h2>
            <div className="prompts-content">
              {prompts}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
